name: Deploy to Development Server

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to deploy (optional)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.pr_number != '' && format('refs/pull/{0}/head', github.event.inputs.pr_number) || github.head_ref }}
    
    - name: Setup remote directory
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEV_VPS_HOST }}
        username: ubuntu
        password: ${{ secrets.DEV_VPS_PASSWORD }}
        timeout: 120s
        script: |
          echo "Preparando directorio de deploy..."
          mkdir -p ~/component-store-api-dev
          rm -rf ~/component-store-api-dev/*
          echo "Directorio preparado"
    
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_VPS_HOST }}
        username: ubuntu
        password: ${{ secrets.DEV_VPS_PASSWORD }}
        timeout: 300s
        source: "./"
        target: "~/component-store-api-dev/"
        rm: true
        strip_components: 1
    
    - name: Create environment and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEV_VPS_HOST }}
        username: ubuntu
        password: ${{ secrets.DEV_VPS_PASSWORD }}
        timeout: 900s
        script: |
          echo "Navegando al directorio de deploy..."
          cd ~/component-store-api-dev
          
          echo "Creando archivo .env..."
          cat > .env << 'EOL'
          PORT=3000
          PAYPAL_API_CLIENT=${{ secrets.PAYPAL_API_CLIENT }}
          PAYPAL_API_SECRET=${{ secrets.PAYPAL_API_SECRET }}
          PAYPAL_API_URL=https://api.sandbox.paypal.com
          HOST=http://${{ secrets.DEV_VPS_HOST }}:3001
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          NODE_ENV=development
          EOL
          
          echo "Verificando Docker..."
          if ! command -v docker &> /dev/null; then
            echo "Instalando Docker..."
            sudo apt-get update -y
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            echo "Docker instalado correctamente"
          else
            echo "Docker ya esta instalado"
          fi
          
          echo "Creando docker-compose.dev.yaml..."
          cat > docker-compose.dev.yaml << 'EOF'
          version: "3.8"
          
          services:
            api-dev:
              build:
                context: .
                dockerfile: Dockerfile
              container_name: component-store-api-dev
              restart: unless-stopped
              ports:
                - "3001:3000"
              environment:
                NODE_ENV: development
                PORT: 3000
                DATABASE_URL: ${DATABASE_URL}
                PAYPAL_API_CLIENT: ${PAYPAL_API_CLIENT}
                PAYPAL_API_SECRET: ${PAYPAL_API_SECRET}
                PAYPAL_API_URL: ${PAYPAL_API_URL}
                HOST: ${HOST}
                JWT_SECRET: ${JWT_SECRET}
              volumes:
                - ./src/public:/app/src/public:ro
              command: sh -c "npx prisma migrate deploy && npm run dev"
          EOF
          
          echo "Deteniendo contenedores existentes..."
          sudo docker compose -f docker-compose.dev.yaml down 2>/dev/null || true
          
          echo "Construyendo nueva imagen..."
          sudo docker compose -f docker-compose.dev.yaml build --no-cache
          
          echo "Iniciando contenedores..."
          sudo docker compose -f docker-compose.dev.yaml up -d
          
          echo "Esperando que el servicio este listo..."
          sleep 30
          
          echo "Estado de contenedores:"
          sudo docker ps | grep component-store-api-dev || echo "Contenedor no encontrado"
          
          echo "Ejecutando migraciones de base de datos..."
          sudo docker compose -f docker-compose.dev.yaml exec -T api-dev npx prisma migrate deploy 2>/dev/null || echo "Migraciones completadas o no necesarias"
          
          echo "Limpiando recursos no utilizados..."
          sudo docker image prune -f >/dev/null 2>&1
          sudo docker system prune -f >/dev/null 2>&1
          
          echo "Deploy completado exitosamente!"
    
    - name: Verify deployment health
      run: |
        echo "Verificando el estado de la aplicacion..."
        
        # Multiples intentos de verificacion
        for attempt in {1..8}; do
          echo "Intento $attempt/8..."
          
          if curl -f -s --connect-timeout 10 --max-time 30 http://${{ secrets.DEV_VPS_HOST }}:3001/api-docs >/dev/null 2>&1; then
            echo "Aplicacion respondiendo correctamente!"
            echo "URL: http://${{ secrets.DEV_VPS_HOST }}:3001/api-docs"
            exit 0
          else
            echo "Aplicacion aun no responde, esperando..."
            sleep 15
          fi
        done
        
        echo "La aplicacion no responde despues de 2 minutos"
        echo "Verifica los logs con: docker logs component-store-api-dev"
        exit 0